name: squadup
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  image_picker: ^1.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # ✅ Add this

flutter:
  uses-material-design: true

  assets:
    - assets/logoo.png
    - assets/mainLogo.jpg
    - assets/default_avatar.png
    - assets/volleyball.png
    - assets/ball.png
    - assets/basketball.png

flutter_icons:  # ✅ Add this to generate launcher icon
  android: true
  ios: true
  image_path: "assets/mainLogo.jpg"  # ✅ Path to your icon image
  min_sdk_android: 21

