name: squadup
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_crashlytics: ^5.0.0
  firebase_analytics: ^12.0.0
  firebase_messaging: ^16.0.0
  image_picker: ^1.1.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.1.5
  cached_network_image: ^3.3.1
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^7.0.1
  intl: ^0.20.2
  
  # Enhanced Authentication & Security
  local_auth: ^2.2.0
  flutter_secure_storage: ^9.0.0
  
  # Notifications (temporarily disabled due to build issues)
  # flutter_local_notifications: ^13.0.0
  
  # UI Enhancement
  lottie: ^2.7.0
  shimmer: ^3.0.0
  confetti: ^0.7.0
  
  # State Management
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  
  # HTTP Client
  http: ^1.1.0
  dio: ^5.4.0
  
  # Security & Crypto
  crypto: ^3.0.3
  
  # Path provider for file operations
  path_provider: ^2.1.5
  
  # Accessibility & Testing
  # integration_test:
  #   sdk: flutter
  
  # Internationalization
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Location services
  geolocator: ^13.0.1
  
  # Firebase

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.9.0
  flutter_gen_runner: ^5.5.0
  mockito: ^5.4.4
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

  assets:
    - assets/images/logoo.png
    - assets/default_avatar.png
    - assets/google_logo.png
    - assets/icons/volleyball.png
    - assets/icons/basketball.png
    - assets/icons/ball.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logoo.png"
  min_sdk_android: 24

