name: squadup
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  image_picker: ^1.1.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  cached_network_image: ^3.3.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  intl: ^0.20.2
  
  # State Management
  flutter_riverpod: ^2.6.1
  go_router: ^14.0.0
  freezed_annotation: ^2.4.0
  json_annotation: ^4.9.0
  
  # HTTP Client
  http: ^1.1.0
  
  # Path provider for file operations
  path_provider: ^2.1.2
  
  # Accessibility & Testing
  integration_test:
    sdk: flutter
  
  # Internationalization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.7
  freezed: ^2.4.0
  json_serializable: ^6.9.0
  flutter_gen_runner: ^5.5.0
  mockito: ^5.4.4
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/logoo.png
    - assets/mainLogo.jpg
    - assets/default_avatar.png
    - assets/volleyball.png
    - assets/ball.png
    - assets/basketball.png
    - assets/google_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/mainLogo.jpg"
  min_sdk_android: 21

