// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5OiCrMOQtjRSDi-KnBb8mnVjHjapk2T8',
    appId: '1:414224011433:web:82e8490ca13299ec3799b8',
    messagingSenderId: '414224011433',
    projectId: 'squadup2-16413',
    authDomain: 'squadup2-16413.firebaseapp.com',
    storageBucket: 'squadup2-16413.firebasestorage.app',
    measurementId: 'G-6F09G0558H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdgTXxOm2hmboNi8I6yLA_3vXoYrvQQyk',
    appId: '1:414224011433:android:1f71eb9a6b5b2e923799b8',
    messagingSenderId: '414224011433',
    projectId: 'squadup2-16413',
    storageBucket: 'squadup2-16413.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASr9c12tEE3OyW_j5eo3R2ZSrI4fPfsrs',
    appId: '1:414224011433:ios:a554f18bf8b3b3523799b8',
    messagingSenderId: '414224011433',
    projectId: 'squadup2-16413',
    storageBucket: 'squadup2-16413.firebasestorage.app',
    iosBundleId: 'com.example.squadup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASr9c12tEE3OyW_j5eo3R2ZSrI4fPfsrs',
    appId: '1:414224011433:ios:a554f18bf8b3b3523799b8',
    messagingSenderId: '414224011433',
    projectId: 'squadup2-16413',
    storageBucket: 'squadup2-16413.firebasestorage.app',
    iosBundleId: 'com.example.squadup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5OiCrMOQtjRSDi-KnBb8mnVjHjapk2T8',
    appId: '1:414224011433:web:d3f2773a13b42c2b3799b8',
    messagingSenderId: '414224011433',
    projectId: 'squadup2-16413',
    authDomain: 'squadup2-16413.firebaseapp.com',
    storageBucket: 'squadup2-16413.firebasestorage.app',
    measurementId: 'G-55F25GMET3',
  );
}
